input_format:
    col_first_name: 2
    col_last_name: 1
    col_id: 0
    col_date: 4
    col_shift: 5
    row_start: 3
settings:
    hours_for_lunch: 5
    lunch_after: 5
paths:
    output: '<HOME_FOLDER>\Desktop\ScheduleHelper'
    footers: 'Footer'
    employee_data: 'Settings'
    default: '<HOME_FOLDER>\Downloads'